#!/usr/bin/env python3
# Generate Chinese email combining key takeaways, sellside highlights, and podcast summaries

import os
from datetime import datetime

# Test with specific date
test_date = '2025-08-29'

# Create output directory
os.makedirs('data/7_emails', exist_ok=True)

# Read the three data sources
key_takeaway = open(f'data/6_final_mds/{test_date}_key_takeaway.md', 'r', encoding='utf-8').read()
sellside = open(f'data/6_final_mds/{test_date}_sellside_highlights.md', 'r', encoding='utf-8').read()

# Read all podcast summaries
podcast_content = []
podcast_dir = f'podcast/{test_date}'
for file in os.listdir(podcast_dir):
    if file.endswith('.md'):
        content = open(f'{podcast_dir}/{file}', 'r', encoding='utf-8').read()
        podcast_content.append(content)

# Simple markdown to HTML conversion
def md_to_html(text):
    html = text.replace('\n## ', '\n<h3>').replace('\n# ', '\n<h2>')
    html = html.replace('\n### ', '\n<h4>').replace('\n- ', '\n<li>')
    html = html.replace('**', '<strong>').replace('*', '<em>')
    html = html.replace('[', '<a href="').replace('](', '">').replace(')', '</a>')
    return html.replace('\n\n', '</p><p>').replace('\n', '<br>')

# Generate HTML email
html_email = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>自动驾驶行业周报 - {test_date}</title>
<style>
body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
h2 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
h3 {{ color: #34495e; margin-top: 25px; }}
h4 {{ color: #7f8c8d; margin-top: 20px; }}
li {{ margin: 8px 0; line-height: 1.6; }}
a {{ color: #3498db; text-decoration: none; }}
.section {{ margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 8px; }}
.header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; text-align: center; }}
</style>
</head>
<body>
<div class="header">
<h1>自动驾驶行业周报</h1>
<p>周期：{test_date}</p>
</div>

<div class="section">
<h2>第一部分：本周关键新闻要点</h2>
<p>{md_to_html(key_takeaway)}</p>
</div>

<div class="section">
<h2>第二部分：券商研究报告精选</h2>
<p>{md_to_html(sellside)}</p>
</div>

<div class="section">
<h2>第三部分：播客摘要</h2>
{''.join([f'<div style="margin: 20px 0;"><p>{md_to_html(pc)}</p></div>' for pc in podcast_content])}
</div>

<div style="text-align: center; margin-top: 40px; padding: 20px; background: #ecf0f1; border-radius: 8px;">
<p>此邮件由自动化系统生成 | Generated by AutoNews System</p>
</div>
</body>
</html>"""

# Save HTML email
output_file = f'data/7_emails/{test_date}_email_chinese.html'
with open(output_file, 'w', encoding='utf-8') as f:
    f.write(html_email)

print(f"✅ Email generated: {output_file}")
print(f"📊 Content: {len(key_takeaway.split('\\n'))} lines from key takeaway, {len(sellside.split('\\n'))} lines from sellside, {len(podcast_content)} podcasts")